# Site configurations
site:

    # Site title
    title: Peanut

    # Site logo
    # logo: /path/to/your/site/logo

    # Site cover
    # cover: /path/to/your/site/cover

    # Base url
    # url: http://peanut.zorro.im

    # Description
    description: Another peanut blog

# Author configurations
author:

    # Author name
    name: Your Name

    # Author avatar url
    # avatar: /path/to/your/avatar

    # Author url
    # url: /posts/about.html

    # Author bio
    # bio: your bio

    # Author location
    # location: Beijing, China


# Path configurations
# path:
    # Draft path
    # draft: drafts

    # Post url template
    # post: posts/{slug}.html

    # Tag url template
    # tag: tags/{title}/

    # Pagination url template
    # pagination: page/{num}/

    # Sitemap url
    # sitemap: sitemap.xml

    # RSS url
    # rss: rss.xml

    # Assert files url
    # asset: /assets/

# Whether to create sitemap or not
# sitemap: True

# Whether to create rss or not
# rss: True

# Theme name or path
# theme: default

# How many posts each page.
# pagination: 10
